media:
  input: src/uploads
  output: /dist/uploads
content:
  - name: verhalen
    label: Stories
    type: collection
    path: src/content/verhalen
    view:
      fields: [title]
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: location
        label: Location
        type: object
        fields:
          - name: lat
            label: Latitude
            type: number
          - name: lng
            label: Longitude
            type: number

      - name: audio
        label: Audio
        type: file
        options:
          categories: [audio]

      - name: images
        label: Images
        type: file
        options:
          categories: [image]
          multiple:
            max: 10

      - name: body
        label: Body
        type: rich-text
