media:
  input: src/uploads
  output: /dist/uploads
content:
  - name: verhalen
    label: Stories
    type: collection
    path: src/content/verhalen
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: location, label: Location, type: string }
      - { name: audio, label: Audio, type: image, categories: [audio] }
      - { name: body, label: Body, type: rich-text }
  
