media:
  input: src/uploads
  output: uploads
# media:
#   - name: audio
#     label: Audio
#     input: src/uploads/audio
#     output: uploads/audio
#     categories: [audio]
#   - name: images
#     label: Images
#     input: src/uploads/img
#     output: uploads/img
#     categories: [image]
content:
  - name: verhalen
    label: Stories
    type: collection
    path: src/content/verhalen
    view:
      fields: [title]
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: location
        label: Location
        type: object
        fields:
          - name: lat
            label: Latitude
            type: number
          - name: lng
            label: Longitude
            type: number

      - name: audio
        label: Audio
        type: file
        options:
          categories: [audio]

      - name: images
        label: Images
        type: image
        options:
          multiple: true

      - name: body
        label: Body
        type: rich-text
