media:
  input: src/uploads
  output: /dist/uploads
content:
  - name: verhalen
    label: Stories
    type: collection
    path: src/content/verhalen
    view:
      fields: [title]
    fields:
      - name: title
      label: Title
      type: string
      required: true 
      - name: coordinates
      label: Coordinates
      type: object
      fields: [
        - name: lat, 
          label: Latitude, 
          type: number, 
          required: true
        - name: lng
          label: Longitude
          type: number
          required: true
